spring.datasource.url=jdbc:h2:file:./data/quizdb;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
app.reports.save-to-disk=true
app.reports.dir=reports

quiz.difficulty.default-mix=MIXED_STANDARD
quiz.difficulty.mixes.MIXED_STANDARD=1:3:2
quiz.difficulty.mixes.MIXED_HARDCORE=0:2:4
quiz.difficulty.mixes.MIXED_EASYGOING=3:2:1
quiz.difficulty.mixes.MIXED_WRONG=1:1:1

calculator.type=fixed-order
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true

spring.cache.type=caffeine

#logging.level.com.jakubroks.quiz.service=ERROR
logging.level.com.jakubroks.quiz.service.QuizCacheService=DEBUG